import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";

const FAQ = () => {
  return (
    <div className="container mt-5 Faq">
      <h2 className="text-center fw-bold">Frequently Asked Questions</h2>
      <div className="accordion mt-4" id="faqAccordion">
        {/* FAQ 1 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
           How Does Aniquest work?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Aniques AI works by leveraging machine learning algorithms to process data...
          </p>
        </details>

        {/* FAQ 2 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            What texts can you generate with Aniquest?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Yes, our AI can generate long-form content, but specificity improves results...
          </p>
        </details>

        {/* FAQ 3 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            How does the Aniquest AI work?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Our AI is trained to develop long texts. Be specific for better results.
          </p>
        </details>

        {/* FAQ 4 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            Can I try Aniquest for free?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Yes, Aniquest offers a free trial to explore its features.
          </p>
        </details>

        {/* FAQ 5 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            Can the AI write stories or posts of +1000 words?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Absolutely, the AI is capable of writing extensive content effectively.
          </p>
        </details>

        {/* FAQ 6 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            Is the content generated by Aniquest AI original?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            Yes, Aniquest generates unique and plagiarism-free content.
          </p>
        </details>

        {/* FAQ 7 */}
        <details className="faq-card mb-3 p-3 rounded shadow-sm bg-light">
          <summary className="btn w-100 text-start d-flex justify-content-between align-items-center">
            How can I make the AI check my texts?
            <span className="faq-icon">+</span>
          </summary>
          <p className="faq-answer p-3">
            You can paste your text into our editor and let the AI evaluate and optimize it.
          </p>
        </details>
      </div>
    </div>
  );
};

export default FAQ;
